version: '2.2'
services:
  carddesign-frontend:
    image: registry.dzcardsolutions.com/carddesign:latest
    container_name: carddesign-frontend
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8044:80'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
